load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
cc_binary(
    name = "tournament",
    srcs = ["tournament.cpp"],
    deps = ["//src/engine", "//src/bot:ga_bot"],
    copts = ["-std=c++17", "-O3", "-pthread"],
    linkopts = ["-pthread"],
)

cc_binary(
    name = "fast_tournament",
    srcs = ["fast_tournament.cpp"],
    deps = ["//src/engine", "//src/bot:ga_bot"],
    copts = ["-std=c++17", "-O3", "-pthread"],
    linkopts = ["-pthread"],
)
cc_binary(
    name = "mega_tournament",
    srcs = ["mega_tournament.cpp"],
    deps = ["//src/engine", "//src/bot:ga_bot"],
    copts = ["-std=c++17", "-O3", "-pthread"],
    linkopts = ["-pthread"],
)
